services:
    glory_admin.admin:
        class: Glory\Bundle\AdminBundle\Variable\Admin
        arguments: [@service_container, @glory_menu.twig.extension]
    
    glory_admin.twig.version_extension:
        class: Glory\Bundle\AdminBundle\Twig\Extension\VersionExtension
        tags:
            - { name: twig.extension }
    glory_admin.twig.admin_extension:
        class: Glory\Bundle\AdminBundle\Twig\Extension\AdminExtension
        arguments: [@glory_admin.admin]
        tags:
            - { name: twig.extension }
    glory_admin.util.logout_url_generator:
        class: Glory\Bundle\AdminBundle\Util\LogoutUrlGenerator
        parent: "security.firewall.map"
        public: true
        calls:
            - [setSecurityLogout,[@security.logout_url_generator]]
    
    glory_admin.menu.default_provider:
        class: Glory\Bundle\AdminBundle\Menu\Provider\DefaultProvider
        arguments: [@glory_menu.menu_manager, @router]
        tags:
          - { name: knp_menu.provider }

    glory_admin.event.pagination_listener:
        class: Glory\Bundle\AdminBundle\EventListener\PaginationListener
        arguments: [@glory_admin.admin]
        tags:
            -  { name: kernel.event_subscriber }