services:
    glory_admin.admin:
        class: Glory\Bundle\AdminBundle\Model\Admin
        arguments: [@service_container]
    
    glory_admin.twig.version_extension:
        class: Glory\Bundle\AdminBundle\Twig\Extension\VersionExtension
        tags:
            - { name: twig.extension }
    glory_admin.twig.admin_extension:
        class: Glory\Bundle\AdminBundle\Twig\Extension\AdminExtension
        arguments: [@glory_admin.admin]
        tags:
            - { name: twig.extension }
    glory_admin.util.logout_url_generator:
        class: Glory\Bundle\AdminBundle\Util\LogoutUrlGenerator
        parent: "security.firewall.map"
        public: true
        calls:
            - [setSecurityLogout,[@security.logout_url_generator]]
